version: '3'
services:
  jupyter:
    image: jupyter-notebook
    build:
      context: .
      dockerfile: jupyter-notebook.Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan
    environment:
      - MASTER=spark://spark-master:7077
      - SPARK_OPTS=--jars /spark-cassandra-connector-assembly-2.3.2-15-g60b513ac.jar --conf spark.cassandra.connection.host=db-cassandra
      - GRANT_SUDO=yes
    links:
      - spark-master
      - db-cassandra
  
  db-cassandra:
    image: cassandra

  spark-master:
    image: spark-base
    build:
      context: .
      dockerfile: spark-base.Dockerfile
    hostname: spark-master
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 127.0.0.1
    links:
      - db-cassandra
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./conf/spark-master:/conf
      - ./data:/tmp/data

  spark-worker:
    image: spark-base
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-1
    environment: 
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 127.0.0.1
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_WORKER_DIR: /work
    links:
      - spark-master
      - db-cassandra
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
      - 8081
    volumes:
      - ./conf/spark-worker:/conf
      - ./data:/tmp/data

  